#ifndef __BSP_ENCOEDER_H
#define __BSP_ENCOEDER_H

#include "stm32f4xx.h"
#include "sys.h"

/* 定时器选择 */
#define ENCODER_TIM TIM2
#define ENCODER_TIM_CLK_ENABLE() __HAL_RCC_TIM2_CLK_ENABLE()

#define ENCODER_TIM_2 TIM3
#define ENCODER_TIM_CLK_ENABLE_2() __HAL_RCC_TIM3_CLK_ENABLE()

#define ENCODER_TIM_3 TIM4
#define ENCODER_TIM_CLK_ENABLE_3() __HAL_RCC_TIM4_CLK_ENABLE()

#define ENCODER_TIM_4 TIM5
#define ENCODER_TIM_CLK_ENABLE_4() __HAL_RCC_TIM5_CLK_ENABLE()

/* 定时器溢出值 */
#define ENCODER_TIM_PERIOD 0XFFFF

#define ENCODER_TIM_PERIOD_2 0XFFFF

#define ENCODER_TIM_PERIOD_3 0XFFFF

#define ENCODER_TIM_PERIOD_4 0XFFFF
/* 定时器预分频值 */
#define ENCODER_TIM_PRESCALER 0

#define ENCODER_TIM_PRESCALER_2 0

#define ENCODER_TIM_PRESCALER_3 0

#define ENCODER_TIM_PRESCALER_4 0

/* 定时器中断 */
#define ENCODER_TIM_IRQn TIM2_IRQn
#define ENCODER_TIM_IRQHandler TIM2_IRQHandler

#define ENCODER_TIM_IRQn_2 TIM3_IRQn
#define ENCODER_TIM_IRQHandler_2 TIM3_IRQHandler

#define ENCODER_TIM_IRQn_3 TIM4_IRQn
#define ENCODER_TIM_IRQHandler TIM4_IRQHandler

#define ENCODER_TIM_IRQn_4 TIM5_IRQn
#define ENCODER_TIM_IRQHandler_2 TIM5_IRQHandler

/* 编码器接口引脚 */
#define ENCODER_TIM_CH1_GPIO_CLK_ENABLE() __HAL_RCC_GPIOA_CLK_ENABLE()
#define ENCODER_TIM_CH1_GPIO_PORT GPIOA
#define ENCODER_TIM_CH1_PIN GPIO_PIN_15
#define ENCODER_TIM_CH1_GPIO_AF GPIO_AF1_TIM2
#define ENCODER_TIM_CH2_GPIO_CLK_ENABLE() __HAL_RCC_GPIOB_CLK_ENABLE()
#define ENCODER_TIM_CH2_GPIO_PORT GPIOB
#define ENCODER_TIM_CH2_PIN GPIO_PIN_3
#define ENCODER_TIM_CH2_GPIO_AF GPIO_AF1_TIM2

#define ENCODER_TIM_CH1_GPIO_CLK_ENABLE_2() __HAL_RCC_GPIOA_CLK_ENABLE()
#define ENCODER_TIM_CH1_GPIO_PORT_2 GPIOA
#define ENCODER_TIM_CH1_PIN_2 GPIO_PIN_6
#define ENCODER_TIM_CH1_GPIO_AF_2 GPIO_AF2_TIM3
#define ENCODER_TIM_CH2_GPIO_CLK_ENABLE_2() __HAL_RCC_GPIOA_CLK_ENABLE()
#define ENCODER_TIM_CH2_GPIO_PORT_2 GPIOA
#define ENCODER_TIM_CH2_PIN_2 GPIO_PIN_7
#define ENCODER_TIM_CH2_GPIO_AF_2 GPIO_AF2_TIM3

#define ENCODER_TIM_CH1_GPIO_CLK_ENABLE_3() __HAL_RCC_GPIOB_CLK_ENABLE()
#define ENCODER_TIM_CH1_GPIO_PORT_3 GPIOB
#define ENCODER_TIM_CH1_PIN_3 GPIO_PIN_6
#define ENCODER_TIM_CH1_GPIO_AF_3 GPIO_AF2_TIM4
#define ENCODER_TIM_CH2_GPIO_CLK_ENABLE_3() __HAL_RCC_GPIOB_CLK_ENABLE()
#define ENCODER_TIM_CH2_GPIO_PORT_3 GPIOB
#define ENCODER_TIM_CH2_PIN_3 GPIO_PIN_7
#define ENCODER_TIM_CH2_GPIO_AF_3 GPIO_AF2_TIM4

#define ENCODER_TIM_CH1_GPIO_CLK_ENABLE_4() __HAL_RCC_GPIOA_CLK_ENABLE()
#define ENCODER_TIM_CH1_GPIO_PORT_4 GPIOA
#define ENCODER_TIM_CH1_PIN_4 GPIO_PIN_0
#define ENCODER_TIM_CH1_GPIO_AF_4 GPIO_AF2_TIM5
#define ENCODER_TIM_CH2_GPIO_CLK_ENABLE_4() __HAL_RCC_GPIOA_CLK_ENABLE()
#define ENCODER_TIM_CH2_GPIO_PORT_4 GPIOA
#define ENCODER_TIM_CH2_PIN_4 GPIO_PIN_1
#define ENCODER_TIM_CH2_GPIO_AF_4 GPIO_AF2_TIM5

/* 编码器接口倍频数 */
#define ENCODER_MODE TIM_ENCODERMODE_TI12

#define ENCODER_MODE_2 TIM_ENCODERMODE_TI12

#define ENCODER_MODE_3 TIM_ENCODERMODE_TI12

#define ENCODER_MODE_4 TIM_ENCODERMODE_TI12

/* 编码器软件滤波值 */
#define ENCODER_FILTER_VALUE 15

#define ENCODER_FILTER_VALUE_2 15

#define ENCODER_FILTER_VALUE_3 15

#define ENCODER_FILTER_VALUE_4 15

/* 编码器接口输入捕获通道相位设置 */
// #define ENCODER_IC1_POLARITY TIM_ICPOLARITY_RISING
// #define ENCODER_IC2_POLARITY_2 TIM_ICPOLARITY_RISING

// #define ENCODER_IC1_POLARITY TIM_ICPOLARITY_RISING
// #define ENCODER_IC2_POLARITY_2 TIM_ICPOLARITY_RISING

/* 读取编码器的频率 单位Hz */
#define READ_ENCODER_FREQU 100

/* 编码器物理分辨率 */
#define ENCODER_RESOLUTION 11

/* 经过倍频之后的总分辨率 */
#if (ENCODER_MODE == TIM_ENCODERMODE_TI12)
#define ENCODER_TOTAL_RESOLUTION (ENCODER_RESOLUTION * 4) /* 4倍频后的总分辨率 */
#else
#define ENCODER_TOTAL_RESOLUTION (ENCODER_RESOLUTION * 2) /* 2倍频后的总分辨率 */
#endif

/* 减速电机减速比 */
#define REDUCTION_RATIO 30

/* 轮胎直径 单位M */
#define TIRE_DIAMETER 0.065

/* 计算转一圈的距离 单位M */
#define ONE_WHEEL_CIRCUMFERENCE (3.14159265358979323846 * TIRE_DIAMETER)

void Encoder_Init(void);
int Read_Encoder(u8 tim);
double Calculate_Velocity(int encoder_value);

#endif /* __BSP_ENCODER_H */